#+TITLE: Agenda
#+OPTIONS: toc:nil

Use Ctrl-c Ctrl-s to set (a schedule) date on a TODO item. This indicates a start date of sorts.
Ctrl-c Ctrl-d can additionally be used to set a deadline.

Both these options opens up a calendar and a date can be selected (using Shift+arrow keys)

Use Ctrl-c [ to add the current file to the top of the agenda file list, otherwise you won't see anything in the agenda view.

Agenda can be viewed using SPC o a (in Doom emacs), and you can go back and forth in time using =[= and =]= keys.
There might not be a keyboard shortcut for every action in Doom emacs so click on the bottom right corner text (Major mode) and it will open up a menu that has several options.


* Things to do
** TODO First item to be done soon
SCHEDULED: <2020-09-02 Wed> DEADLINE: <2020-09-14 Mon>
** TODO Another thing that can be done next month
SCHEDULED: <2020-10-04 Sun>
** TODO This thing's gonna go on for a few hours
SCHEDULED: <2020-09-04 Fri>

* Repeating tasks
** TODO Gotta do this every week
SCHEDULED: <2020-09-19 Sat +1w>
:PROPERTIES:
:LAST_REPEAT: [2020-09-09 Wed 15:59]
:END:
- State "DONE"       from "TODO"       [2020-09-09 Wed 15:59]
Add a =+1w= within the schedule date to make a task to repeat each week. Marking it done will show the next date it is due with all dates it has been already marke done for underneath.
** TODO Only do this in the future
SCHEDULED: <2020-09-01 Tue ++1w>
Tasks which have =++= will only schedule tasks in the future, skipping any dates in the past.
** TODO Relative delta in schedules
SCHEDULED: <2020-09-03 Thu .+1w>
By default, the next date for repeating task is the delta from the scheduled date. Adding a =.= makes the next scheduled date according to the date it was completed on. If a weekly task was scheduled for today but I completed it 2 days later. The next task will be 1 week from when I completed it. (And not 5 days later as originally scheduled)
